language: cpp
compiler:
  - gcc
  - clang

before_install:
  - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get update -qq; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
  - wget -O Qt5.2.0.tar.xz https://dl.dropboxusercontent.com/u/20447449/Qt5.2.0.tar.xz
  - mkdir ~/Qt5.2.0
  - tar -xJf Qt5.2.0.tar.xz -C ~/Qt5.2.0
  - sudo chmod -R 777 ~/Qt5.2.0/
  - ln -s ~/Qt5.2.0/5.2.0/gcc_64/mkspecs/linux-g++ ~/Qt5.2.0/5.2.0/gcc_64/mkspecs/linux-gcc
  # - git clone git://github.com/jedisct1/libsodium.git
  # - cd libsodium
  # - git checkout tags/0.5.0
  # - ./autogen.sh
  # - ./configure
  # - make -j$(nproc)
  # - sudo make install
  # - sudo ldconfig
  # - cd ..
  # - git clone git://github.com/irungentoo/ProjectTox-Core.git
  # - cd ProjectTox-Core
  # - autoreconf -i
  # - ./configure --disable-tests
  # - make -j$(nproc)
  # - sudo make install
  # - sudo ldconfig
  # - cd ..

script:
  - cd plugins
  - ~/Qt5.2.0/5.2.0/gcc_64/bin/qmake plugins.pro
  - make -j$(proc)
  - cd ..
  - ~/Qt5.2.0/5.2.0/gcc_64/bin/qmake mini-pint.pro
  - make -j$(proc)
  # - ~/Qt5.2.0/5.2.0/gcc_64/bin/qmake -v
  # - ~/Qt5.2.0/5.2.0/gcc_64/bin/qmake -spec linux-$CC -Wall projectfiles/QtCreator/TOX-Qt-GUI.pro
  # - make -j$(nproc)

notifications:
  irc:
    channels:
      - "chat.freenode.net##manhtu"
    on_success: always
    on_failure: always